#!/usr/bin/env python

import sys
import rospy
import tic_tac_toe.game_agent

from tic_tac_toe.srv import *

if __name__ == "__main__":
    rospy.init_node("interaction_manager")
    rospy.wait_for_service('execute_game_action')
    executor = rospy.ServiceProxy('execute_game_action', ExecuteGameAction)
    rospy.spin()
    
    # Wait for start signal
    
    # Loop:
    #   Get game state from vision and detect change
    #   If game is done, end
    #   Calculate move
    #   Execute move with current experimental manipulation
